export const koLang = {
  'Type something': '내용을 입력하세요',
  'About Jodit': 'Jodit 에디터 정보',
  'Jodit Editor': 'Jodit 에디터',
  'Free Non-commercial Version': '무료 비상업적 버전',
  'GNU General Public License, version 2 or later': 'GNU 일반 공중 사용 허가서, 버전 2 이상',
  'Jodit User\'s Guide': 'Jodit 사용자 가이드',
  'contains detailed help for using': '사용에 대한 자세한 도움말이 포함되어 있습니다',
  'For information about the license, please go to our website:': '라이선스에 대한 정보는 웹사이트를 참조하세요:',
  'Buy full version': '정식 버전 구매',
  'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.': 'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.',

  // Toolbar buttons
  'Bold': '굵게',
  'Italic': '기울임',
  'Underline': '밑줄',
  'Strike through': '취소선',
  'Subscript': '아래 첨자',
  'Superscript': '위 첨자',
  'Cut': '잘라내기',
  'Copy': '복사',
  'Paste': '붙여넣기',
  'Insert Unordered List': '순서 없는 목록 삽입',
  'Insert Ordered List': '순서 있는 목록 삽입',
  'Decrease Indent': '들여쓰기 줄이기',
  'Increase Indent': '들여쓰기 늘리기',
  'Select all': '모두 선택',
  'Source': '소스',
  'Wrap': '줄 바꿈',
  'Undo': '실행 취소',
  'Redo': '다시 실행',
  'Fullsize': '전체 화면',
  'Shrink': '축소',
  'HR': '수평선',
  'Left': '왼쪽 정렬',
  'Center': '가운데 정렬',
  'Right': '오른쪽 정렬',
  'Justify': '양쪽 정렬',
  'Insert link': '링크 삽입',
  'Insert image': '이미지 삽입',
  'Insert file': '파일 삽입',
  'Insert youtube/vimeo video': 'YouTube/Vimeo 동영상 삽입',
  'Insert table': '표 삽입',
  'Eraser': '지우개',
  'Copy format': '서식 복사',
  'Font size': '글꼴 크기',
  'Font family': '글꼴',
  'Insert Special Character': '특수 문자 삽입',
  'Format': '서식',
  'Normal': '일반',
  'Heading 1': '제목 1',
  'Heading 2': '제목 2',
  'Heading 3': '제목 3',
  'Heading 4': '제목 4',
  'Quote': '인용',
  'Code': '코드',

  // Colors
  'Background': '배경색',
  'Text color': '글자색',
  'Reset': '재설정',
  'Save': '저장',
  'Save as ...': '다른 이름으로 저장...',
  'Resize': '크기 조정',
  'Crop': '자르기',
  'Width': '너비',
  'Height': '높이',
  'Keep Aspect Ratio': '비율 유지',
  'Yes': '예',
  'No': '아니오',
  'Remove': '제거',
  'Select': '선택',
  'Vertical align': '세로 정렬',
  'Horizontal align': '가로 정렬',
  'Filter': '필터',
  'Browse': '찾아보기',
  'Upload': '업로드',
  'Cancel': '취소',
  'Apply': '적용',
  'Alternative text': '대체 텍스트',
  'Link': '링크',
  'Open in new tab': '새 탭에서 열기',
  'Open editor in fullscreen': '전체 화면으로 에디터 열기',
  'Clear Formatting': '서식 지우기',
  'Fill color or set the text color': '채우기 색상 또는 텍스트 색상 설정',
  'Align': '정렬',
  'Lists': '목록',
  'Break': '줄 바꿈',
  'Search for': '검색',
  'Replace with': '바꿀 내용',
  'Replace': '바꾸기',
  'Replace all': '모두 바꾸기',
  'Find': '찾기',
  'Find Previous': '이전 찾기',
  'Find Next': '다음 찾기',

  // File browser
  'Files': '파일',
  'Drop image': '이미지를 드롭하세요',
  'Drop file': '파일을 드롭하세요',
  'or click': '또는 클릭하세요',
  'Upload image': '이미지 업로드',
  'Upload file': '파일 업로드',

  // Table
  'Insert row above': '위에 행 삽입',
  'Insert row below': '아래에 행 삽입',
  'Insert column before': '앞에 열 삽입',
  'Insert column after': '뒤에 열 삽입',
  'Delete row': '행 삭제',
  'Delete column': '열 삭제',
  'Delete table': '표 삭제',
  'Empty cell': '빈 셀',

  // Symbols
  'Symbol': '기호',
  'Symbols': '기호',

  // Other
  'Print': '인쇄',
  'Preview': '미리보기',
  'Please fill out this field': '이 필드를 채워주세요',
  'Please enter a web address': '웹 주소를 입력하세요',
  'Default': '기본값',
  'Disc': '디스크',
  'Square': '사각형',
  'Lower Alpha': '소문자',
  'Lower Greek': '그리스 소문자',
  'Lower Roman': '로마 소문자',
  'Upper Alpha': '대문자',
  'Upper Roman': '로마 대문자',

  // Paste
  'Your browser doesn\'t support direct access to the clipboard.': '브라우저가 클립보드에 직접 액세스를 지원하지 않습니다.',
  'Copy selection': '선택 영역 복사',
  'Paste from clipboard': '클립보드에서 붙여넣기',
  'Paste Special': '선택하여 붙여넣기',
  'Keep only text': '텍스트만 유지',

  // Drag and Drop
  'Drop to upload': '업로드하려면 드롭하세요',

  // Resize
  'Resize box': '크기 조정 상자',
  'Resize image': '이미지 크기 조정',

  // Toolbar
  'Toolbar': '도구 모음',
  'Open': '열기',

  // Status bar
  'Words: %d': '단어: %d',
  'Chars: %d': '문자: %d',
  'Chars without spaces: %d': '공백 제외 문자: %d',

  // About
  'About': '정보',
  'License': '라이선스',
  'Jodit Editor is released under': 'Jodit 에디터는 다음 라이선스로 배포됩니다',
  'Version': '버전',
  'Author': '작성자',
  'Website': '웹사이트',
  'Email': '이메일',

  // Error messages
  'Error on load list': '목록 로드 오류',
  'Error on load folders': '폴더 로드 오류',
  'Are you sure?': '확실합니까?',
  'Enter Directory name': '디렉토리 이름 입력',
  'Create directory': '디렉토리 생성',
  'type name': '이름 입력',
  'Drop files': '파일 드롭',
  'or': '또는',
  'Browse files': '파일 찾아보기',
  'Error 404': '오류 404',
  'Error 500': '오류 500',
  'Error 403': '오류 403',
  'Download': '다운로드',
  'Rename': '이름 바꾸기',
  'Edit': '편집',
  'Delete': '삭제',
  'Select Image': '이미지 선택',
  'Select File': '파일 선택',
  'Folder name': '폴더 이름',
  'File name': '파일 이름',
  'Size': '크기',
  'Date modified': '수정 날짜',
  'Loading...': '로딩 중...',
  'Reload': '새로고침',
  'First': '첫 번째',
  'Previous': '이전',
  'Next': '다음',
  'Last': '마지막',
  'Upload files': '파일 업로드',
  'File uploaded': '파일 업로드됨',
  'Upload failed': '업로드 실패',

  // Image editor
  'Image Editor': '이미지 편집기',
  'Crop Image': '이미지 자르기',
  'Resize Image': '이미지 크기 조정',
  'Save as PNG': 'PNG로 저장',
  'Save as JPG': 'JPG로 저장',
  'Save as GIF': 'GIF로 저장',
  'Quality': '품질',
  'Transparency': '투명도',
  'Brightness': '밝기',
  'Contrast': '대비',
  'Saturation': '채도',
  'Hue': '색조',
  'Blur': '흐림',
  'Sharpen': '선명하게',
  'Emboss': '양각',
  'Grayscale': '회색조',
  'Invert': '반전',
  'Sepia': '세피아',
  'Vintage': '빈티지',
  'Noise': '노이즈',
  'Pixelate': '픽셀화',
  'Mosaic': '모자이크',
  'Oil painting': '유화',
  'Cartoon': '만화',
  'Pencil': '연필',
  'Watercolor': '수채화',
  'Sketch': '스케치',
  'Posterize': '포스터화',
  'Solarize': '솔라라이즈',
  'Threshold': '임계값',
  'Gamma': '감마',
  'Exposure': '노출',
  'Highlights': '하이라이트',
  'Shadows': '그림자',
  'Vibrance': '생동감',
  'Temperature': '색온도',
  'Tint': '색조',
  'Vignette': '비네트',
  'Lens flare': '렌즈 플레어',
  'Red eye': '적목 현상',
  'Rotate': '회전',
  'Flip horizontal': '수평 뒤집기',
  'Flip vertical': '수직 뒤집기',
  'Clone': '복제',
  'Healing': '치유',
  'Dodge': '닷지',
  'Burn': '번',
  'Sponge': '스펀지',
  'Smudge': '번짐',
  'Text': '텍스트',
  'Line': '선',
  'Arrow': '화살표',
  'Rectangle': '사각형',
  'Circle': '원',
  'Polygon': '다각형',
  'Brush': '브러시',
  'Pencil tool': '연필 도구',
  'Eraser tool': '지우개 도구',
  'Fill': '채우기',
  'Gradient': '그라데이션',
  'Eyedropper': '스포이드',
  'Zoom': '확대/축소',
  'Hand': '손',
  'Move': '이동',
  'Lasso': '올가미',
  'Magic wand': '마법 지팡이',
  'Free transform': '자유 변형',
  'Liquify': '액화',
  'Puppet warp': '퍼펫 워프',
  'Content aware': '내용 인식',
  'Patch': '패치',
  'Red eye removal': '적목 현상 제거',
  'Spot healing': '스팟 치유',
  'Clone stamp': '복제 스탬프',
  'Healing brush': '치유 브러시',
  'History brush': '히스토리 브러시',
  'Art history brush': '아트 히스토리 브러시',
  'Pattern stamp': '패턴 스탬프',
  'Color replacement': '색상 교체',
  'Mixer brush': '믹서 브러시',
  'Dodge tool': '닷지 도구',
  'Burn tool': '번 도구',
  'Sponge tool': '스펀지 도구',
  'Smudge tool': '번짐 도구',
  'Pen tool': '펜 도구',
  'Freeform pen': '자유형 펜',
  'Add anchor point': '앵커 포인트 추가',
  'Delete anchor point': '앵커 포인트 삭제',
  'Convert point': '포인트 변환',
  'Path selection': '패스 선택',
  'Direct selection': '직접 선택',
  'Type tool': '타입 도구',
  'Vertical type': '세로 타입',
  'Type mask': '타입 마스크',
  'Vertical type mask': '세로 타입 마스크',
  'Line tool': '선 도구',
  'Rectangle tool': '사각형 도구',
  'Rounded rectangle': '둥근 사각형',
  'Ellipse tool': '타원 도구',
  'Polygon tool': '다각형 도구',
  'Custom shape': '사용자 정의 모양',
  'Notes': '메모',
  'Audio annotation': '오디오 주석',
  'Eyedropper tool': '스포이드 도구',
  'Color sampler': '색상 샘플러',
  'Ruler': '눈금자',
  'Count': '카운트',
  'Hand tool': '손 도구',
  'Zoom tool': '확대/축소 도구',
  'Rotate view': '보기 회전',
  'Default foreground': '기본 전경색',
  'Default background': '기본 배경색',
  'Switch foreground': '전경색 전환',
  'Standard mode': '표준 모드',
  'Quick mask mode': '빠른 마스크 모드',
  'Change screen mode': '화면 모드 변경',
  'Jump to ImageReady': 'ImageReady로 이동'
};